### ISSUE TITLE
File

### ISSUE THREAD

**Issue by Camirgz** [Camirgz/WebScrapingProject#2]
### Goal
---
The goal is that everytime the program runs, it creates a .csv document,  it should include the results table ( #1 ) and the date and time the program was used

### To-Do List
---
- [ ]  Create table branch
- [ ]  Decide which library or program is the one to be used
- [ ]  Understand how it works
- [ ]  Make the code
- [ ]  Commit and push final code
